//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.CodeDom.Compiler;
using System.Collections.Specialized;
using System.Configuration;
using System.Diagnostics;
using System.Drawing;
using System.Runtime.CompilerServices;

namespace ganjoor.Properties {
    
    
    [CompilerGenerated()]
    [GeneratedCode("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.0.3.0")]
    internal sealed partial class Settings : ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("10")]
        public int SearchPageItems {
            get {
                return ((int)(this["SearchPageItems"]));
            }
            set {
                this["SearchPageItems"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("0")]
        public int LastCat {
            get {
                return ((int)(this["LastCat"]));
            }
            set {
                this["LastCat"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("0")]
        public int LastPoem {
            get {
                return ((int)(this["LastPoem"]));
            }
            set {
                this["LastPoem"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("")]
        public string LastSearchPhrase {
            get {
                return ((string)(this["LastSearchPhrase"]));
            }
            set {
                this["LastSearchPhrase"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("0")]
        public int LastSeachStart {
            get {
                return ((int)(this["LastSeachStart"]));
            }
            set {
                this["LastSeachStart"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool WindowMaximized {
            get {
                return ((bool)(this["WindowMaximized"]));
            }
            set {
                this["WindowMaximized"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("0, 0")]
        public Point WindowLocation {
            get {
                return ((Point)(this["WindowLocation"]));
            }
            set {
                this["WindowLocation"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("0, 0")]
        public Size WindowSize {
            get {
                return ((Size)(this["WindowSize"]));
            }
            set {
                this["WindowSize"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("Tahoma, 8.25pt")]
        public Font ViewFont {
            get {
                return ((Font)(this["ViewFont"]));
            }
            set {
                this["ViewFont"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool HighlightKeyword {
            get {
                return ((bool)(this["HighlightKeyword"]));
            }
            set {
                this["HighlightKeyword"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool WasShowingFavs {
            get {
                return ((bool)(this["WasShowingFavs"]));
            }
            set {
                this["WasShowingFavs"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool BrowseButtonVisible {
            get {
                return ((bool)(this["BrowseButtonVisible"]));
            }
            set {
                this["BrowseButtonVisible"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool CommentsButtonVisible {
            get {
                return ((bool)(this["CommentsButtonVisible"]));
            }
            set {
                this["CommentsButtonVisible"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("True")]
        public bool CopyButtonVisible {
            get {
                return ((bool)(this["CopyButtonVisible"]));
            }
            set {
                this["CopyButtonVisible"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool PrintButtonVisible {
            get {
                return ((bool)(this["PrintButtonVisible"]));
            }
            set {
                this["PrintButtonVisible"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool ShowBeytNums {
            get {
                return ((bool)(this["ShowBeytNums"]));
            }
            set {
                this["ShowBeytNums"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("True")]
        public bool ShowNumsVisible {
            get {
                return ((bool)(this["ShowNumsVisible"]));
            }
            set {
                this["ShowNumsVisible"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("500")]
        public int MaxPoemsInList {
            get {
                return ((int)(this["MaxPoemsInList"]));
            }
            set {
                this["MaxPoemsInList"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("0")]
        public int LastCatStart {
            get {
                return ((int)(this["LastCatStart"]));
            }
            set {
                this["LastCatStart"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("True")]
        public bool GradiantBackground {
            get {
                return ((bool)(this["GradiantBackground"]));
            }
            set {
                this["GradiantBackground"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("LightGray")]
        public Color GradiantBegin {
            get {
                return ((Color)(this["GradiantBegin"]));
            }
            set {
                this["GradiantBegin"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("White")]
        public Color GradiantEnd {
            get {
                return ((Color)(this["GradiantEnd"]));
            }
            set {
                this["GradiantEnd"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("Window")]
        public Color BackColor {
            get {
                return ((Color)(this["BackColor"]));
            }
            set {
                this["BackColor"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("")]
        public string BackImagePath {
            get {
                return ((string)(this["BackImagePath"]));
            }
            set {
                this["BackImagePath"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("ControlText")]
        public Color TextColor {
            get {
                return ((Color)(this["TextColor"]));
            }
            set {
                this["TextColor"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool CheckForUpdate {
            get {
                return ((bool)(this["CheckForUpdate"]));
            }
            set {
                this["CheckForUpdate"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("0")]
        public int LastSearchPoetID {
            get {
                return ((int)(this["LastSearchPoetID"]));
            }
            set {
                this["LastSearchPoetID"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("True")]
        public bool HomeButtonVisible {
            get {
                return ((bool)(this["HomeButtonVisible"]));
            }
            set {
                this["HomeButtonVisible"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("True")]
        public bool RandomButtonVisible {
            get {
                return ((bool)(this["RandomButtonVisible"]));
            }
            set {
                this["RandomButtonVisible"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("Blue")]
        public Color LinkColor {
            get {
                return ((Color)(this["LinkColor"]));
            }
            set {
                this["LinkColor"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("Purple")]
        public Color CurrentLinkColor {
            get {
                return ((Color)(this["CurrentLinkColor"]));
            }
            set {
                this["CurrentLinkColor"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("Red")]
        public Color HighlightColor {
            get {
                return ((Color)(this["HighlightColor"]));
            }
            set {
                this["HighlightColor"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("True")]
        public bool IsNewVersion {
            get {
                return ((bool)(this["IsNewVersion"]));
            }
            set {
                this["IsNewVersion"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("Red")]
        public Color BandLinkColor {
            get {
                return ((Color)(this["BandLinkColor"]));
            }
            set {
                this["BandLinkColor"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("True")]
        public bool ScrollToFavedVerse {
            get {
                return ((bool)(this["ScrollToFavedVerse"]));
            }
            set {
                this["ScrollToFavedVerse"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("0")]
        public int ViewMode {
            get {
                return ((int)(this["ViewMode"]));
            }
            set {
                this["ViewMode"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("10")]
        public int FavItemsInPage {
            get {
                return ((int)(this["FavItemsInPage"]));
            }
            set {
                this["FavItemsInPage"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("3")]
        public int ScrollingSpeed {
            get {
                return ((int)(this["ScrollingSpeed"]));
            }
            set {
                this["ScrollingSpeed"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool EditorButtonVisible {
            get {
                return ((bool)(this["EditorButtonVisible"]));
            }
            set {
                this["EditorButtonVisible"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("")]
        public string HttpProxyServer {
            get {
                return ((string)(this["HttpProxyServer"]));
            }
            set {
                this["HttpProxyServer"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("")]
        public string HttpProxyPort {
            get {
                return ((string)(this["HttpProxyPort"]));
            }
            set {
                this["HttpProxyPort"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("24")]
        public string RandomCats {
            get {
                return ((string)(this["RandomCats"]));
            }
            set {
                this["RandomCats"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("True")]
        public bool DownloadButtonVisible {
            get {
                return ((bool)(this["DownloadButtonVisible"]));
            }
            set {
                this["DownloadButtonVisible"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        public StringCollection CustomDownloadUrls {
            get {
                return ((StringCollection)(this["CustomDownloadUrls"]));
            }
            set {
                this["CustomDownloadUrls"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        public StringCollection CustomDownloadListNames {
            get {
                return ((StringCollection)(this["CustomDownloadListNames"]));
            }
            set {
                this["CustomDownloadListNames"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        public StringCollection CustomDownloadListDescriptions {
            get {
                return ((StringCollection)(this["CustomDownloadListDescriptions"]));
            }
            set {
                this["CustomDownloadListDescriptions"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("http://i.ganjoor.net/android/androidgdbs.xml")]
        public string LastDownloadUrl {
            get {
                return ((string)(this["LastDownloadUrl"]));
            }
            set {
                this["LastDownloadUrl"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        public StringCollection CustomDownloadListMoreInfoUrls {
            get {
                return ((StringCollection)(this["CustomDownloadListMoreInfoUrls"]));
            }
            set {
                this["CustomDownloadListMoreInfoUrls"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("")]
        public string DownloadPath {
            get {
                return ((string)(this["DownloadPath"]));
            }
            set {
                this["DownloadPath"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("True")]
        public bool DeleteDownloadedFiles {
            get {
                return ((bool)(this["DeleteDownloadedFiles"]));
            }
            set {
                this["DeleteDownloadedFiles"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool DbIsIndexed {
            get {
                return ((bool)(this["DbIsIndexed"]));
            }
            set {
                this["DbIsIndexed"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("")]
        public string SoundsPath {
            get {
                return ((string)(this["SoundsPath"]));
            }
            set {
                this["SoundsPath"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("Poet")]
        public string ExportLevel {
            get {
                return ((string)(this["ExportLevel"]));
            }
            set {
                this["ExportLevel"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool ExportPoetName {
            get {
                return ((bool)(this["ExportPoetName"]));
            }
            set {
                this["ExportPoetName"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool ExportCatName {
            get {
                return ((bool)(this["ExportCatName"]));
            }
            set {
                this["ExportCatName"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("True")]
        public bool ExportPoemName {
            get {
                return ((bool)(this["ExportPoemName"]));
            }
            set {
                this["ExportPoemName"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("===")]
        public string ExportPoemSep {
            get {
                return ((string)(this["ExportPoemSep"]));
            }
            set {
                this["ExportPoemSep"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("---")]
        public string ExportCatSep {
            get {
                return ((string)(this["ExportCatSep"]));
            }
            set {
                this["ExportCatSep"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("***")]
        public string ExportPoetSep {
            get {
                return ((string)(this["ExportPoetSep"]));
            }
            set {
                this["ExportPoetSep"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("")]
        public string MuseumToken {
            get {
                return ((string)(this["MuseumToken"]));
            }
            set {
                this["MuseumToken"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("https://api.ganjoor.net")]
        public string GanjoorServiceUrl {
            get {
                return ((string)(this["GanjoorServiceUrl"]));
            }
            set {
                this["GanjoorServiceUrl"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("0")]
        public int LastSearchType {
            get {
                return ((int)(this["LastSearchType"]));
            }
            set {
                this["LastSearchType"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("0")]
        public int LastSearchLocationType {
            get {
                return ((int)(this["LastSearchLocationType"]));
            }
            set {
                this["LastSearchLocationType"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("00000000-0000-0000-0000-000000000000")]
        public Guid SessionId {
            get {
                return ((Guid)(this["SessionId"]));
            }
            set {
                this["SessionId"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("")]
        public string DefProfile {
            get {
                return ((string)(this["DefProfile"]));
            }
            set {
                this["DefProfile"] = value;
            }
        }
    }
}
